apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jenkins-exam.fullname" . }}
  labels:
    {{- include "jenkins-exam.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "jenkins-exam.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jenkins-exam.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "jenkins-exam.serviceAccountName" . }}
      containers:
        - name: movie-service
          image: "{{ .Values.movie.image.repository }}:{{ .Values.movie.image.tag }}"
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "{{ .Values.env.DATABASE_URL }}"

        - name: cast-service
          image: "{{ .Values.cast.image.repository }}:{{ .Values.cast.image.tag }}"
          ports:
            - containerPort: 8001
