apiVersion: v1
kind: Service
metadata:
  name: {{ include "jenkins-exam.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "jenkins-exam.name" . }}
  ports:
    - name: http
      port: 80
      targetPort: 8000
      nodePort: {{ .Values.service.nodePort }}

