apiVersion: v1
kind: Service
metadata:
  name: {{ include "jenkins-exam.fullname" . }}
spec:
  type: NodePort
  selector:
    app: {{ include "jenkins-exam.name" . }}
  ports:
    - port: 80
      targetPort: 8000
      nodePort: {{ .Values.service.nodePort }}

