apiVersion: v1
kind: Service
metadata:
  name: {{ include "jenkins-exam.fullname" . }}
  labels:
    {{- include "jenkins-exam.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "jenkins-exam.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{- if eq .Values.service.type "NodePort" }} {{ .Values.service.nodePort }} {{- end }}
      protocol: TCP
