replicaCount: 3

movie:
  image:
    repository: wafajemai/jenkins-devops
    tag: "movie.prod"

cast:
  image:
    repository: wafajemai/jenkins-devops
    tag: "cast.prod"


serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: false

ingress:
  enabled: false
