replicaCount: 1

movie:
  image:
    repository: wafajemai/jenkins-devops
    tag: "movie.latest"

cast:
  image:
    repository: wafajemai/jenkins-devops
    tag: "cast.latest"

service:
  type: NodePort
  port: 80
  targetPort: 8000

env:
  DATABASE_URL: "sqlite:////data/db.sqlite3"

ingress:
  enabled: false

autoscaling:
  enabled: false

serviceAccount:
  create: true

