replicaCount: 2

movie:
  image:
    tag: movie.prod

cast:
  image:
    tag: cast.prod

service:
  type: NodePort
  port: 80
  targetPort: 8000
  nodePort: 30084

env:
  DATABASE_URL: "sqlite:///./app/api/db.sqlite3"

serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: false

ingress:
  enabled: false

