replicaCount: 2

movie:
  image:
    repository: wafajemai/jenkins-devops
    tag: "movie.qa"

cast:
  image:
    repository: wafajemai/jenkins-devops
    tag: "cast.qa"

serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: false

ingress:
  enabled: false
