replicaCount: 1

movie:
  image:
    tag: movie.dev

cast:
  image:
    tag: cast.dev

service:
  type: NodePort
  port: 80
  targetPort: 8000
  nodePort: 31124

env:
  DATABASE_URL: "sqlite:///./app/api/db.sqlite3"

serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: false

ingress:
  enabled: false

