replicaCount: 1

movie:
  image:
    repository: wafajemai/jenkins-devops
    tag: "movie.dev"

cast:
  image:
    repository: wafajemai/jenkins-devops
    tag: "cast.dev"

service:
  type: NodePort
  port: 80
  nodePort: 30081
  targetPort: 8000

env:
  DATABASE_URL: "sqlite:///./app/api/db.sqlite3"

