replicaCount: 2

movie:
  image:
    repository: wafajemai/jenkins-devops
    tag: "movie.qa"

cast:
  image:
    repository: wafajemai/jenkins-devops
    tag: "cast.qa"

service:
  type: NodePort
  port: 80
  nodePort: 30082
  targetPort: 8000

env:
  - name: DATABASE_URL
    value: "sqlite:///./app/api/db.sqlite3"
