replicaCount: 2

movie:
  image:
    repository: wafajemai/jenkins-devops
    tag: "movie.staging"

cast:
  image:
    repository: wafajemai/jenkins-devops
    tag: "cast.staging"


serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: false

ingress:
  enabled: false
