replicaCount: 1

movie:
  image:
    repository: wafajemai/jenkins-devops
    tag: movie.qa
    pullPolicy: IfNotPresent

cast:
  image:
    repository: wafajemai/jenkins-devops
    tag: cast.qa
    pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 8000
  nodePort: 31125

env:
  DATABASE_URL: "sqlite:///./app/api/db.sqlite3"

serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: false

ingress:
  enabled: false

